import { NextApiRequest, NextApiResponse } from "next";
import { getSession } from "next-auth/react";

import { stripe } from "../../services/stripe";

export default async function subscribe(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method === "POST") {
    // Getting user from Cookies using next-auth becauses
    // remember: local storage is NOT available on server-side, just on client-side
    const session = await getSession({ req });

    // Creating to get the ID generated by stripe e repass it
    const stripeCustomer = await stripe.customers.create({
      email: session.user.email
    })

    const stripeCheckoutSession = await stripe.checkout.sessions.create({
      customer: stripeCustomer.id,
      payment_method_types: ["card"],
      success_url: process.env.STRIPE_SUCCESS_URL,
      cancel_url: process.env.STRIPE_CANCEL_URL,
      billing_address_collection: "required",
      allow_promotion_codes: true,
      line_items: [
        {
          price: "price_1KqQw8CXCCDs6rb5omQK8m6I",
          quantity: 1
        }
      ],
      mode: "subscription"
    })

    res.status(200).json({ sessionId: stripeCheckoutSession.id });
  } else {
    res.setHeader("Allow", "POST")
    res.status(405).end("Method not allowed");
  }
}
