import { NextApiRequest, NextApiResponse } from "next";
import { getSession } from "next-auth/react";
import { query } from "faunadb";

import { stripe } from "../../services/stripe";
import { faunadb } from "../../services/faunadb";

type User = {
  ref: {
    id: string;
  },
  data: {
    stripe_customer_id
  }
}

export default async function subscribe(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method === "POST") {
    // Getting user from Cookies using next-auth becauses
    // remember: local storage is NOT available on server-side, just on client-side
    const session = await getSession({ req });

    const user = await faunadb.query<User>(
      query.Get(
        query.Match(
          query.Index("user_by_email"),
          query.Casefold(session.user.email)
        )
      )
    );

    let customerId = user.data.stripe_customer_id;

    if (!customerId) {
      // Creating to get the ID generated by stripe e repass it
      const stripeCustomer = await stripe.customers.create({
        email: session.user.email
      })

      await faunadb.query(
        query.Update(
          query.Ref(
            query.Collection("users"),
            user.ref.id
          ),
          {
            data: {
              stripe_customer_id: stripeCustomer.id
            }
          }
        )
      );

      customerId = stripeCustomer.id;
    }

    const stripeCheckoutSession = await stripe.checkout.sessions.create({
      customer: customerId,
      payment_method_types: ["card"],
      success_url: process.env.STRIPE_SUCCESS_URL,
      cancel_url: process.env.STRIPE_CANCEL_URL,
      billing_address_collection: "required",
      allow_promotion_codes: true,
      line_items: [
        {
          price: "price_1KqQw8CXCCDs6rb5omQK8m6I",
          quantity: 1
        }
      ],
      mode: "subscription"
    })

    res.status(200).json({ sessionId: stripeCheckoutSession.id });
  } else {
    res.setHeader("Allow", "POST")
    res.status(405).end("Method not allowed");
  }
}
